version: '3'
services:
  python-app:
    container_name: team-tesla-backend
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/team-tesla-backend
